openapi: 3.0.2
info:
  title: LectureMT API
  description: Translate lecture texts from Japanese to English.
  version: '1.0'
  contact:
    name: Frederic Bergeron
    email: bergeron@nlp.ist.i.kyoto-u.ac.jp
  license:
    name: GPL 3.0
servers:
- url: '$API_BASE_URL/$VIRTUAL_DIR/api/1.0'
  description: Production server
- url: '$API_BASE_URL/$VIRTUAL_DIR/api/1.0'
  description: Development server
paths:
  /api-version:
    get:
      summary: Returns the version of the API.
      responses:
        200:
          description: "Succesful operation."
  /server-version:
    get:
      summary: Returns the version of the server.
      responses:
        200:
          description: "Succesful operation."
  /server-status:
    get:
      summary: Returns the server status (load, current tranlations, etc.)
      responses:
        200:
          description: "Succesful operation."
  /translation_queues:
    get:
      summary: Returns the translation queues.
      responses:
        200:
          description: "Succesful operation."
  /translation_queue/{id}:
    get:
      summary: Return the translation queue.
      parameters:
      - name: "id"
        in: "path"
        description: "Identifier of the translation queue."
        required: true
        schema:
          type: string
      responses:
        200:
          description: "Succesful operation."
  /translations:
    get:
      summary: Returns the list of translations.
      responses:
        200:
          description: "Succesful operation."
  /translation:
    post:
      summary: Submits a new translation.
      requestBody:
        description: A translation request expressed in JSON.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslationRequest'
      responses:
        201:
          description: "Created."
        400:
          description: "Invalid request."
  /translation/{id}:
    get:
      summary: Obtains information about a translation.
      parameters:
      - name: "id"
        in: "path"
        description: "Identifier of the translation."
        required: true
        schema:
          type: string
      responses:
        200:
          description: "Succesful operation."
        404:
          description: "Translation not found."
    delete:
      summary: Removes/cancels a translation.
      parameters:
      - name: "id"
        in: "path"
        description: "Identifier of the translation."
        required: true
        schema:
          type: string
      responses:
        204:
          description: "Translation deleted."
        default:
          description: "Unexpected error."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    TranslationRequest:
      title: A Translation Request
      type: object
      properties:
        lang_source:
          type: string
          description: 2-letters code expressing the source language (ja for Japanese).
        lang_target:
          type: string
          description: 2-letters code expressing the target language (en for English).
        text_source:
          type: string
          description: Text to be translated.
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          
          
